// cta.component.ts
import { Component, Input } from '@angular/core'

@Component({
  selector: 'app-cta',
  templateUrl: 'cta.component.html',
  styleUrls: ['cta.component.css'],
})
export class CTA {
  @Input()
  heading1: string = 'Start Managing Your Farm Supplies Efficiently'
  @Input()
  content1: string =
    'Track, monitor, and sell your agricultural products with ease on our platform.'
  @Input()
  action1: string = 'Sign Up Now'
  constructor() {}
}

<div class="thq-section-padding">
  <div class="thq-section-max-width">
    <div class="cta-accent2-bg">
      <div class="cta-accent1-bg">
        <div class="cta-container1">
          <div class="cta-content">
            <span class="thq-heading-2">{{ heading1 }}</span>
            <p class="thq-body-large">{{ content1 }}</p>
          </div>
          <div class="cta-actions">
            <button type="button" class="thq-button-filled cta-button">
              {{ action1 }}
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// cta.vue
<template>
  <div class="thq-section-padding">
    <div class="thq-section-max-width">
      <div class="cta-accent2-bg">
        <div class="cta-accent1-bg">
          <div class="cta-container1">
            <div class="cta-content">
              <span class="thq-heading-2">{{ heading1 }}</span>
              <p class="thq-body-large">{{ content1 }}</p>
            </div>
            <div class="cta-actions">
              <button type="button" class="thq-button-filled cta-button">
                {{ action1 }}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'CTA',
  props: {
    heading1: {
      type: String,
      default: 'Start Managing Your Farm Supplies Efficiently',
    },
    content1: {
      type: String,
      default:
        'Track, monitor, and sell your agricultural products with ease on our platform.',
    },
    action1: {
      type: String,
      default: 'Sign Up Now',
    },
  },
}
</script>

<style scoped>
.cta-accent2-bg {
  gap: var(--dl-space-space-oneandhalfunits);
  display: flex;
  transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(1deg) skew(0deg, 0deg);
  align-self: stretch;
  transition: 0.3s;
  align-items: center;
  border-radius: var(--dl-radius-radius-cardradius);
  justify-content: space-between;
  transform-style: preserve-3d;
  background-color: var(--dl-color-theme-accent2);
}
.cta-accent2-bg:hover {
  transform: scale3d(1.1,1.1,1.1);
}
.cta-accent1-bg {
  width: 100%;
  display: flex;
  transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(-2deg) skew(0deg, 0deg);
  align-items: center;
  border-radius: var(--dl-radius-radius-cardradius);
  justify-content: space-between;
  transform-style: preserve-3d;
  background-color: var(--dl-color-theme-accent1);
}
.cta-container1 {
  gap: var(--dl-space-space-threeunits);
  width: 100%;
  display: flex;
  transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(1deg) skew(0deg, 0deg);
  transition: 0.3s;
  align-items: center;
  padding-top: var(--dl-space-space-sixunits);
  padding-left: var(--dl-space-space-fourunits);
  border-radius: var(--dl-radius-radius-cardradius);
  padding-right: var(--dl-space-space-fourunits);
  padding-bottom: var(--dl-space-space-sixunits);
}
.cta-container1:hover {
  color: var(--dl-color-theme-neutral-light);
  background-color: var(--dl-color-theme-neutral-dark);
}
.cta-content {
  gap: var(--dl-space-space-oneandhalfunits);
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.cta-actions {
  gap: var(--dl-space-space-oneandhalfunits);
  flex: 1;
  display: flex;
  align-items: flex-start;
  justify-content: flex-end;
}
@media(max-width: 767px) {
  .cta-container1 {
    gap: var(--dl-space-space-oneandhalfunits);
    flex-direction: column;
    justify-content: flex-start;
  }
}
@media(max-width: 479px) {
  .cta-actions {
    flex-wrap: wrap;
    align-self: stretch;
    justify-content: center;
  }
  .cta-button {
    flex: 1;
  }
}
</style>
